Docary/Docary/Areas/Desktop/Controllers/EntryController.cs
using Docary.Services;

namespace Docary.Areas.Desktop.Controllers
{
    public class EntryController : Docary.Areas.Shared.Controllers.EntryController
    {
        public EntryController(IEntryService entryService) : base(entryService) { }
    }
}

Docary/Docary/Areas/Mobile/Controllers/EntryController.cs
using Docary.Services;

namespace Docary.Areas.Mobile.Controllers
{
    public class EntryController : Docary.Areas.Shared.Controllers.EntryController
    {
        public EntryController(IEntryService entryService) : base(entryService) { }
    }
}

Docary/Docary/Areas/Shared/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Docary.MvcExtensions;
using Docary.Services;
using Docary.ViewModels;
using Docary.ViewModelExtractors;

namespace Docary.Areas.Shared.Controllers
{
    public class EntryController : DocaryController
    {
        private IEntryService _entryService;

        public EntryController(IEntryService entryService)
        {
            _entryService = entryService;
        }

        [Authorize]
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Add(AddEntryViewModel addEntryViewModel)
        {
            if (ModelState.IsValid)
            {
                var entry = addEntryViewModel.ExtractEntry();
                entry.UserId = UserId;

                _entryService.AddEntry(entry);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(addEntryViewModel);
            }
        }
    }
}

Docary/Docary/Areas/Mobile/Views/Entry/Add.cshtml
@{
    ViewBag.Title = "Add entry";
}

@model Docary.ViewModels.AddEntryViewModel
        
@using (Html.BeginForm("Add", "Entry"))
{                    
    @Html.ValidationSummary(false, "Adding entry was unsuccessful. Please correct the errors and try again.")                
    <div data-role="fieldcontain">
        @Html.LabelFor(m => m.Description, "Description")
        @Html.TextAreaFor(m => m.Description)
    </div>   
    <div data-role="fieldcontain">
        @Html.LabelFor(m => m.TagName, "Tag")
        @Html.TextBoxFor(m => m.TagName) 
    </div>        
    <div data-role="fieldcontain">
        @Html.LabelFor(m => m.LocationName, "Location")
        @Html.TextBoxFor(m => m.LocationName) 
    </div>        
    <p>
        <input type="submit" value="Add" />
    </p>        
}

@section Footer {
    @{ Html.RenderPartial("_FooterLoggedOn"); }
}